---
name: Check Them Vim Files

on: # yamllint disable-line
  # push:
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Linting
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.x"
      - name: Install Vint
        run: |
          python -m pip install --upgrade pip setuptools "setuptools<82" wheel
          pip install --upgrade vim-vint
      - name: Vinting code
        run: vint --verbose --stat $(find . -type f -name '*.vim')
